server:
  port: 6001

spring:
  application:
     name: gateway-zuul
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.223.142:9411/
