server:
  port: 6001

spring:
  application:
      name: gateway-zuul
  rabbitmq: 
      host: 192.168.223.142
      username: guest
      password: guest
      port: 5672
zuul: 
   routes:
     product-server: /productService/**
management: 
   endpoints: 
     web: 
       exposure: 
           include: "*"
   endpoint:
     health: 
       show-details: always