server:
  port: 6001

spring:
  application:
      name: gateway-zuul

eureka:
  client:
     service-url:
        defaultZone: localhost:8762/eureka
  instance:
     instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}