spring:
  application:
     name: product-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/o2o_cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.223.142
    username: guest
    password: guest
    port: 5672
  sleuth: 
     web: 
      client:
         enabled: true
     sampler:
      probability: 1.0 #将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
   zipkin: 
     base-url: http://192.168.223.142:9411/   ## 指定了 Zipkin 服务器的地址

