spring:
  application:
     name: product-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/o2o_cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.223.142
    username: guest
    password: guest
    port: 5672
	
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/ 
  instance:
       instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

